# Netlify Caching Configuration
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Image optimization
[build.processing.images]
  compress = true

# Redirect for www
[[redirects]]
  from = "https://www.alan-henry.co.uk/*"
  to = "https://alan-henry.co.uk/:splat"
  status = 301
  force = true

# Build settings
[build]
  publish = "dist"
  command = "npm run build"